# fly.toml app configuration file generated for tylermenezes-services on 2024-06-06T14:25:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tylermenezes-services'
primary_region = 'sea'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[experimental]
  auto_rollback = true

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 3000
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 50
    soft_limit = 40

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
