app = "tylermenezes-todoist-automations"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
